package com.sme.erp.accounting.service.impl;
import com.sme.erp.accounting.entity.AccountingPeriod; import com.sme.erp.accounting.enums.AccountingPeriodStatus; import com.sme.erp.accounting.repository.AccountingPeriodRepository; import com.sme.erp.accounting.service.AccountingPeriodService; import com.sme.erp.common.exception.*; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.time.*; import java.util.*;
@Service public class AccountingPeriodServiceImpl implements AccountingPeriodService {private final AccountingPeriodRepository repo;public AccountingPeriodServiceImpl(AccountingPeriodRepository r){repo=r;}
 @Transactional(readOnly=true) public List<AccountingPeriod> all(){return repo.findAllByOrderByStartDateDesc();}
 @Transactional public AccountingPeriod create(AccountingPeriod p){if(p.getStartDate()==null||p.getEndDate()==null||p.getStartDate().isAfter(p.getEndDate()))throw new BadRequestException("Valid period dates are required");if(repo.overlaps(p.getStartDate(),p.getEndDate()))throw new BadRequestException("Accounting period overlaps an existing period");p.setStatus(AccountingPeriodStatus.OPEN);return repo.save(p);}
 @Transactional public AccountingPeriod close(Long id){AccountingPeriod p=find(id);if(p.getStatus()==AccountingPeriodStatus.CLOSED)throw new BadRequestException("Period is already closed");p.setStatus(AccountingPeriodStatus.CLOSED);p.setClosedAt(LocalDateTime.now());p.setClosedBy(user());return repo.save(p);}
 @Transactional public AccountingPeriod reopen(Long id){AccountingPeriod p=find(id);if(p.getStatus()==AccountingPeriodStatus.OPEN)throw new BadRequestException("Period is already open");p.setStatus(AccountingPeriodStatus.OPEN);p.setClosedAt(null);p.setClosedBy(null);return repo.save(p);}
 @Transactional(readOnly=true) public void assertOpen(LocalDate date){if(date!=null&&repo.contains(date,AccountingPeriodStatus.CLOSED))throw new BadRequestException("Accounting period is closed for date: "+date);}
 private AccountingPeriod find(Long id){return repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Accounting period not found"));} private String user(){var a=SecurityContextHolder.getContext().getAuthentication();return a==null?null:a.getName();}
}
