package com.sme.erp.accounting.service.impl;
import com.sme.erp.accounting.dto.*; import com.sme.erp.accounting.entity.*; import com.sme.erp.accounting.enums.*; import com.sme.erp.accounting.repository.*; import com.sme.erp.accounting.service.BudgetService; import com.sme.erp.common.exception.*; import com.sme.erp.common.util.RequestValueUtils; import org.springframework.data.domain.*; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.*; import java.time.*; import java.util.*;
@Service public class BudgetServiceImpl implements BudgetService {
 private static final int BUDGET_NO_ATTEMPTS = 20;
 private final BudgetRepository repo; private final AccountRepository accounts; private final CostCenterRepository centers; private final JournalEntryLineRepository lines;
 public BudgetServiceImpl(BudgetRepository r,AccountRepository a,CostCenterRepository c,JournalEntryLineRepository l){repo=r;accounts=a;centers=c;lines=l;}
 @Transactional(readOnly=true) public Page<BudgetDTO> page(String q,Integer y,BudgetStatus s,int p,int z){return repo.search(RequestValueUtils.normalize(q),y,s,PageRequest.of(Math.max(0,p),Math.min(100,Math.max(1,z)),Sort.by(Sort.Direction.DESC,"id"))).map(this::dto);}
 @Transactional(readOnly=true) public BudgetDTO get(Long id){return dto(find(id));}
 @Transactional public BudgetDTO create(BudgetDTO d){Budget b=new Budget();b.setBudgetNo(nextBudgetNo());fill(b,d);return dto(repo.save(b));}
 @Transactional public BudgetDTO update(Long id,BudgetDTO d){Budget b=find(id);if(b.getStatus()!=BudgetStatus.DRAFT)throw new BadRequestException("Only draft budgets can be edited");fill(b,d);return dto(repo.save(b));}
 @Transactional public BudgetDTO approve(Long id){Budget b=find(id);if(b.getStatus()!=BudgetStatus.DRAFT)throw new BadRequestException("Only draft budgets can be approved");b.setStatus(BudgetStatus.APPROVED);b.setApprovedAt(LocalDateTime.now());b.setApprovedBy(user());return dto(repo.save(b));}
 @Transactional public BudgetDTO cancel(Long id){Budget b=find(id);if(b.getStatus()==BudgetStatus.CANCELLED)throw new BadRequestException("Budget is already cancelled");b.setStatus(BudgetStatus.CANCELLED);return dto(repo.save(b));}
 @Transactional(readOnly=true) public BudgetActualDTO actual(Integer y,LocalDate from,LocalDate to,Long aid,Long cid){LocalDate af=from!=null?from:(y==null?null:LocalDate.of(y,1,1)),at=to!=null?to:(y==null?null:LocalDate.of(y,12,31));List<Budget> bs=repo.approved(y,from,to,aid,cid);Map<Key,BigDecimal> budget=new LinkedHashMap<>(),actual=new LinkedHashMap<>();Map<Key,Account> accountMap=new HashMap<>();Map<Key,CostCenter> centerMap=new HashMap<>();for(Budget b:bs){Key k=new Key(b.getAccount().getId(),b.getCostCenter()==null?null:b.getCostCenter().getId());budget.merge(k,b.getAmount(),BigDecimal::add);accountMap.put(k,b.getAccount());centerMap.put(k,b.getCostCenter());}for(JournalEntryLine l:lines.findPostedLedgerLines(aid,af,at)){Long lc=l.getCostCenter()==null?null:l.getCostCenter().getId();if(cid!=null&&!Objects.equals(cid,lc))continue;Key k=new Key(l.getAccount().getId(),lc);actual.merge(k,normal(l.getAccount(),l),BigDecimal::add);accountMap.put(k,l.getAccount());centerMap.put(k,l.getCostCenter());}Set<Key> keys=new LinkedHashSet<>(budget.keySet());keys.addAll(actual.keySet());List<BudgetActualRowDTO> rows=new ArrayList<>();BigDecimal tb=BigDecimal.ZERO,ta=BigDecimal.ZERO;for(Key k:keys){Account a=accountMap.get(k);CostCenter c=centerMap.get(k);BigDecimal bv=budget.getOrDefault(k,BigDecimal.ZERO),av=actual.getOrDefault(k,BigDecimal.ZERO),variance=bv.subtract(av);BigDecimal pct=bv.signum()==0?BigDecimal.ZERO:variance.multiply(BigDecimal.valueOf(100)).divide(bv,2,RoundingMode.HALF_UP);rows.add(new BudgetActualRowDTO(a.getId(),a.getAccountCode(),a.getAccountName(),c==null?null:c.getId(),c==null?"Unassigned":c.getCode(),c==null?"Unassigned":c.getName(),bv,av,variance,pct));tb=tb.add(bv);ta=ta.add(av);}BigDecimal util=tb.signum()==0?BigDecimal.ZERO:ta.multiply(BigDecimal.valueOf(100)).divide(tb,2,RoundingMode.HALF_UP);return new BudgetActualDTO(rows,tb,ta,tb.subtract(ta),util);}
 private BigDecimal normal(Account a,JournalEntryLine l){return switch(a.getAccountType()){case INCOME,LIABILITY,EQUITY->l.getCredit().subtract(l.getDebit());default->l.getDebit().subtract(l.getCredit());};}
 private String nextBudgetNo(){String prefix="BUD-"+LocalDate.now().format(java.time.format.DateTimeFormatter.BASIC_ISO_DATE)+"-";for(int i=0;i<BUDGET_NO_ATTEMPTS;i++){String candidate=prefix+String.format("%03d",Math.abs(java.util.concurrent.ThreadLocalRandom.current().nextInt(1000)));if(!repo.existsByBudgetNo(candidate))return candidate;}throw new BadRequestException("Unable to generate a unique budget number. Please retry.");}
 private void fill(Budget b,BudgetDTO d){if(d.getFromDate().isAfter(d.getToDate()))throw new BadRequestException("fromDate cannot be after toDate");b.setFiscalYear(d.getFiscalYear());b.setPeriodType(d.getPeriodType());b.setFromDate(d.getFromDate());b.setToDate(d.getToDate());b.setAmount(d.getAmount());b.setAccount(accounts.findById(d.getAccountId()).orElseThrow(()->new ResourceNotFoundException("Account not found")));b.setCostCenter(d.getCostCenterId()==null?null:centers.findById(d.getCostCenterId()).orElseThrow(()->new ResourceNotFoundException("Cost center not found")));}
 private Budget find(Long id){return repo.detailed(id).orElseThrow(()->new ResourceNotFoundException("Budget not found with id: "+id));} private String user(){var a=SecurityContextHolder.getContext().getAuthentication();return a==null?null:a.getName();}
 private BudgetDTO dto(Budget b){BudgetDTO d=new BudgetDTO();d.setId(b.getId());d.setBudgetNo(b.getBudgetNo());d.setFiscalYear(b.getFiscalYear());d.setPeriodType(b.getPeriodType());d.setFromDate(b.getFromDate());d.setToDate(b.getToDate());d.setAccountId(b.getAccount().getId());d.setAccountCode(b.getAccount().getAccountCode());d.setAccountName(b.getAccount().getAccountName());if(b.getCostCenter()!=null){d.setCostCenterId(b.getCostCenter().getId());d.setCostCenterCode(b.getCostCenter().getCode());d.setCostCenterName(b.getCostCenter().getName());}d.setAmount(b.getAmount());d.setStatus(b.getStatus());d.setCreatedAt(b.getCreatedAt());d.setApprovedAt(b.getApprovedAt());d.setApprovedBy(b.getApprovedBy());return d;} private record Key(Long accountId,Long centerId){}
}
