package com.sme.erp.accounting.service.impl;
import com.sme.erp.accounting.entity.*; import com.sme.erp.accounting.enums.*; import com.sme.erp.accounting.repository.*; import com.sme.erp.accounting.service.*; import com.sme.erp.common.exception.*; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.math.*; import java.time.*; import java.util.*;
@Service public class YearEndClosingServiceImpl implements YearEndClosingService {private final YearEndClosingRepository repo;private final AccountRepository accounts;private final JournalEntryRepository journals;private final JournalEntryLineRepository lines;private final AccountingPeriodService periods;
 private static final List<YearEndClosingStatus> ACTIVE_STATUSES=List.of(YearEndClosingStatus.DRAFT,YearEndClosingStatus.COMPLETED);
 public YearEndClosingServiceImpl(YearEndClosingRepository r,AccountRepository a,JournalEntryRepository j,JournalEntryLineRepository l,AccountingPeriodService p){repo=r;accounts=a;journals=j;lines=l;periods=p;}
 @Transactional(readOnly=true) public List<YearEndClosing> all(){return repo.findAllByOrderByFiscalYearDesc();}
 @Transactional public YearEndClosing prepare(Integer year){if(year==null||year<1900)throw new BadRequestException("Valid fiscal year is required");if(repo.existsByFiscalYearAndStatusIn(year,ACTIVE_STATUSES))throw new BadRequestException("Year-end closing already exists for fiscal year "+year+" with draft or completed status");YearEndClosing c=new YearEndClosing();c.setFiscalYear(year);c.setClosingDate(LocalDate.of(year,12,31));c.setRetainedEarningsAmount(net(year));return repo.save(c);}
 @Transactional public YearEndClosing complete(Long id){YearEndClosing c=repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Year-end closing not found"));if(c.getStatus()!=YearEndClosingStatus.DRAFT)throw new BadRequestException("Only draft year-end closing can be completed");if(repo.existsByFiscalYearAndStatus(c.getFiscalYear(),YearEndClosingStatus.COMPLETED))throw new BadRequestException("Year-end closing is already completed for fiscal year "+c.getFiscalYear());periods.assertOpen(c.getClosingDate());c.setRetainedEarningsAmount(net(c.getFiscalYear()));JournalEntry j=closingJournal(c);j=journals.save(j);c.setClosingJournalId(j.getId());c.setStatus(YearEndClosingStatus.COMPLETED);c.setCompletedAt(LocalDateTime.now());c.setCompletedBy(user());return repo.save(c);}
 private JournalEntry closingJournal(YearEndClosing c){LocalDate from=LocalDate.of(c.getFiscalYear(),1,1),to=c.getClosingDate();JournalEntry j=new JournalEntry();j.setJournalNo(nextNo());j.setJournalDate(to);j.setReferenceType("YEAR_END_CLOSING");j.setReferenceNo(String.valueOf(c.getFiscalYear()));j.setDescription("Year-end closing "+c.getFiscalYear());j.setSourceType("YEAR_END_CLOSING");j.setSourceId(c.getId());j.setSourceNo(String.valueOf(c.getFiscalYear()));j.setStatus(JournalStatus.POSTED);BigDecimal profit=BigDecimal.ZERO;for(Account a:accounts.findAll()){BigDecimal d=safe(lines.sumDebit(a.getId(),from,to)),cr=safe(lines.sumCredit(a.getId(),from,to));if(a.getAccountType()==AccountType.INCOME){BigDecimal n=cr.subtract(d);profit=profit.add(n);close(j,a,n,true);}else if(a.getAccountType()==AccountType.EXPENSE){BigDecimal n=d.subtract(cr);profit=profit.subtract(n);close(j,a,n,false);}}Account retained=requiredAccount("3010","Retained Earnings");add(j,retained,profit.signum()<0?profit.abs():BigDecimal.ZERO,profit.signum()>0?profit:BigDecimal.ZERO);return j;}
 private void close(JournalEntry j,Account a,BigDecimal n,boolean income){if(n.signum()==0)return;if(income)add(j,a,n.signum()>0?n:BigDecimal.ZERO,n.signum()<0?n.abs():BigDecimal.ZERO);else add(j,a,n.signum()<0?n.abs():BigDecimal.ZERO,n.signum()>0?n:BigDecimal.ZERO);}
 private void add(JournalEntry j,Account a,BigDecimal d,BigDecimal c){JournalEntryLine l=new JournalEntryLine();l.setAccount(a);l.setDebit(d);l.setCredit(c);l.setDescription("Year-end closing");j.addLine(l);} private BigDecimal net(int y){LocalDate f=LocalDate.of(y,1,1),t=LocalDate.of(y,12,31);BigDecimal n=BigDecimal.ZERO;for(Account a:accounts.findAll()){if(a.getAccountType()==AccountType.INCOME)n=n.add(safe(lines.sumCredit(a.getId(),f,t)).subtract(safe(lines.sumDebit(a.getId(),f,t))));else if(a.getAccountType()==AccountType.EXPENSE)n=n.subtract(safe(lines.sumDebit(a.getId(),f,t)).subtract(safe(lines.sumCredit(a.getId(),f,t))));}return n;} private Optional<Account> resolveAccount(String code,String name){Optional<Account> byCode=accounts.findByAccountCodeIgnoreCase(code);return byCode.isPresent()?byCode:accounts.findByAccountNameIgnoreCase(name);} private Account requiredAccount(String code,String name){return resolveAccount(code,name).orElseThrow(()->new BadRequestException("Required account is missing for year-end closing. Expected account code "+code+" or name "+name));} private String nextNo(){long n=journals.findMaxId()+1;String v=String.format("JRN-%04d",n);while(journals.existsByJournalNo(v))v=String.format("JRN-%04d",++n);return v;}private BigDecimal safe(BigDecimal v){return v==null?BigDecimal.ZERO:v;}private String user(){var a=SecurityContextHolder.getContext().getAuthentication();return a==null?null:a.getName();}
}
