import { Component, OnInit } from '@angular/core';
import { AbstractControl, FormBuilder, FormGroup, ValidationErrors, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { Status } from '../../../models/product.model';
import { Supplier } from '../../../models/supplier.model';
import { SupplierService } from '../../../services/supplier.service';
import { debugApiError, extractApiErrorMessage } from '../../../shared/utils/api-error.util';

@Component({
  selector: 'app-supplier-form',
  templateUrl: './supplier-form.component.html',
  styleUrls: ['./supplier-form.component.css']
})
export class SupplierFormComponent implements OnInit {
  private readonly autoGeneratedCodeLabel = 'Auto generated by backend';

  form: FormGroup;
  loading = false;
  submitting = false;
  isEditMode = false;
  supplierId: number | null = null;
  errorMessage = '';

  readonly statusList: Status[] = ['ACTIVE', 'INACTIVE'];

  constructor(
    private fb: FormBuilder,
    private route: ActivatedRoute,
    private router: Router,
    private supplierService: SupplierService
  ) {
    this.form = this.fb.group({
      supplierCode: [{ value: '', disabled: true }],
      name: ['', [Validators.required, this.notBlankValidator, Validators.maxLength(255)]],
      companyName: ['', [Validators.maxLength(255)]],
      contactPerson: ['', [Validators.maxLength(255)]],
      phone: ['', [Validators.maxLength(100)]],
      email: ['', [Validators.email, Validators.maxLength(255)]],
      address: [''],
      city: ['', [Validators.maxLength(100)]],
      country: ['', [Validators.maxLength(100)]],
      postalCode: ['', [Validators.maxLength(50)]],
      openingBalance: [0, [Validators.min(0)]],
      currentBalance: [{ value: 0, disabled: true }],
      taxNumber: ['', [Validators.maxLength(100)]],
      bankAccount: ['', [Validators.maxLength(255)]],
      paymentTerms: ['', [Validators.maxLength(255)]],
      status: ['ACTIVE', Validators.required]
    });
  }

  ngOnInit(): void {
    const idParam = this.route.snapshot.paramMap.get('id');
    if (idParam) {
      this.supplierId = Number(idParam);
      this.isEditMode = true;
      this.loadSupplier(this.supplierId);
    } else {
      this.form.patchValue({
        supplierCode: this.autoGeneratedCodeLabel,
        openingBalance: 0,
        currentBalance: 0,
        status: 'ACTIVE'
      });
    }
  }

  loadSupplier(id: number): void {
    this.loading = true;
    this.supplierService.getSupplierById(id).subscribe({
      next: (supplier) => {
        this.form.patchValue({
          supplierCode: supplier.supplierCode || this.autoGeneratedCodeLabel,
          name: supplier.name,
          companyName: supplier.companyName || '',
          contactPerson: supplier.contactPerson || '',
          phone: supplier.phone || '',
          email: supplier.email || '',
          address: supplier.address || '',
          city: supplier.city || '',
          country: supplier.country || '',
          postalCode: supplier.postalCode || '',
          openingBalance: supplier.openingBalance ?? 0,
          currentBalance: supplier.currentBalance ?? (supplier.openingBalance ?? 0),
          taxNumber: supplier.taxNumber || '',
          bankAccount: supplier.bankAccount || '',
          paymentTerms: supplier.paymentTerms || '',
          status: supplier.status || 'ACTIVE'
        });
        this.loading = false;
      },
      error: (error) => {
        this.errorMessage = extractApiErrorMessage(error, 'Supplier could not be loaded.');
        this.loading = false;
        debugApiError('SupplierFormComponent.loadSupplier', error);
      }
    });
  }

  submit(): void {
    this.errorMessage = '';
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    const payload = this.buildPayload();
    this.submitting = true;

    const request$ = this.isEditMode && this.supplierId
      ? this.supplierService.updateSupplier(this.supplierId, payload)
      : this.supplierService.createSupplier(payload);

    request$.subscribe({
      next: () => {
        this.submitting = false;
        this.router.navigate(['/suppliers/list']);
      },
      error: (error) => {
        this.submitting = false;
        this.errorMessage = extractApiErrorMessage(error, 'Supplier could not be saved.');
        debugApiError('SupplierFormComponent.submit', error);
      }
    });
  }

  cancel(): void {
    this.router.navigate(['/suppliers/list']);
  }

  hasError(controlName: string, errorName: string): boolean {
    const control = this.form.get(controlName);
    return !!control && control.touched && control.hasError(errorName);
  }

  private buildPayload(): Supplier {
    const value = this.form.getRawValue();
    return {
      supplierCode: this.buildSupplierCode(value.supplierCode),
      name: value.name.trim(),
      companyName: this.optionalTextValue(value.companyName),
      contactPerson: this.optionalTextValue(value.contactPerson),
      phone: this.optionalTextValue(value.phone),
      email: this.optionalTextValue(value.email),
      address: this.optionalTextValue(value.address),
      city: this.optionalTextValue(value.city),
      country: this.optionalTextValue(value.country),
      postalCode: this.optionalTextValue(value.postalCode),
      openingBalance: value.openingBalance === null || value.openingBalance === '' ? 0 : Number(value.openingBalance),
      taxNumber: this.optionalTextValue(value.taxNumber),
      bankAccount: this.optionalTextValue(value.bankAccount),
      paymentTerms: this.optionalTextValue(value.paymentTerms),
      status: value.status
    };
  }

  private notBlankValidator(control: AbstractControl): ValidationErrors | null {
    return typeof control.value === 'string' && control.value.trim().length === 0
      ? { required: true }
      : null;
  }

  private buildSupplierCode(value: string): string | undefined {
    if (!this.isEditMode) {
      return undefined;
    }

    const supplierCode = value?.trim();
    return supplierCode && supplierCode !== this.autoGeneratedCodeLabel
      ? supplierCode
      : undefined;
  }

  private optionalTextValue(value: string): string | null | undefined {
    const normalized = value?.trim();
    if (normalized) {
      return normalized;
    }
    return this.isEditMode ? null : undefined;
  }
}
