package com.sme.erp.accounting.service;

import com.sme.erp.accounting.dto.*; import com.sme.erp.accounting.entity.*; import com.sme.erp.accounting.enums.*; import com.sme.erp.accounting.repository.*; import com.sme.erp.accounting.service.impl.*; import com.sme.erp.common.exception.BadRequestException; import com.sme.erp.enums.Status;
import org.junit.jupiter.api.*; import org.junit.jupiter.api.extension.ExtendWith; import org.mockito.*; import org.mockito.junit.jupiter.MockitoExtension; import java.math.*; import java.time.*; import java.util.*;
import static org.assertj.core.api.Assertions.*; import static org.mockito.ArgumentMatchers.*; import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class) class AccountingBatch3ServiceTest {
 @Mock CostCenterRepository centerRepo; @Mock BudgetRepository budgetRepo; @Mock AccountRepository accountRepo; @Mock JournalEntryLineRepository lineRepo; @Mock AccountingPeriodRepository periodRepo; @Mock YearEndClosingRepository yearRepo; @Mock JournalEntryRepository journalRepo; @Mock AccountingPeriodService periodService;

 @Test void costCenterCreateEditAndDeactivate(){CostCenterServiceImpl s=new CostCenterServiceImpl(centerRepo);when(centerRepo.save(any())).thenAnswer(i->{CostCenter c=i.getArgument(0);if(c.getId()==null)c.setId(1L);return c;});CostCenterDTO created=s.create(new CostCenterDTO(null,"OPS","Operations",null,Status.ACTIVE,null,null));assertThat(created.code()).isEqualTo("OPS");CostCenter entity=center(1L);when(centerRepo.findById(1L)).thenReturn(Optional.of(entity));CostCenterDTO updated=s.update(1L,new CostCenterDTO(1L,"OPS","Ops Team","Updated",Status.ACTIVE,null,null));assertThat(updated.name()).isEqualTo("Ops Team");s.deactivate(1L);assertThat(entity.getStatus()).isEqualTo(Status.INACTIVE);}

 @Test void budgetCreateEditApproveAndCancel(){BudgetServiceImpl s=budgetService();Account a=account(1L,"5000","Expense",AccountType.EXPENSE);when(accountRepo.findById(1L)).thenReturn(Optional.of(a));when(budgetRepo.existsByBudgetNo(anyString())).thenReturn(false);when(budgetRepo.save(any())).thenAnswer(i->{Budget b=i.getArgument(0);if(b.getId()==null)b.setId(10L);return b;});BudgetDTO created=s.create(budgetDto());assertThat(created.getStatus()).isEqualTo(BudgetStatus.DRAFT);assertThat(created.getBudgetNo()).startsWith("BUD-");Budget b=budgetEntity(10L,a,BudgetStatus.DRAFT);when(budgetRepo.detailed(10L)).thenReturn(Optional.of(b));BudgetDTO edited=s.update(10L,budgetDto());assertThat(edited.getAmount()).isEqualByComparingTo("1000");assertThat(s.approve(10L).getStatus()).isEqualTo(BudgetStatus.APPROVED);assertThat(s.cancel(10L).getStatus()).isEqualTo(BudgetStatus.CANCELLED);}

 @Test void budgetCreateRetriesUntilBudgetNumberIsUnique(){BudgetServiceImpl s=budgetService();Account a=account(1L,"5000","Expense",AccountType.EXPENSE);when(accountRepo.findById(1L)).thenReturn(Optional.of(a));when(budgetRepo.existsByBudgetNo(anyString())).thenReturn(true,false);when(budgetRepo.save(any())).thenAnswer(i->{Budget b=i.getArgument(0);b.setId(11L);return b;});BudgetDTO created=s.create(budgetDto());assertThat(created.getBudgetNo()).startsWith("BUD-");verify(budgetRepo,atLeast(2)).existsByBudgetNo(anyString());}

 @Test void budgetVsActualUsesApprovedBudgetAndPostedLines(){BudgetServiceImpl s=budgetService();Account a=account(1L,"5000","Expense",AccountType.EXPENSE);Budget b=budgetEntity(1L,a,BudgetStatus.APPROVED);when(budgetRepo.approved(2026,null,null,null,null)).thenReturn(List.of(b));when(lineRepo.findPostedLedgerLines(null,LocalDate.of(2026,1,1),LocalDate.of(2026,12,31))).thenReturn(List.of(line(a,"600","0",null)));BudgetActualDTO r=s.actual(2026,null,null,null,null);assertThat(r.totalBudget()).isEqualByComparingTo("1000");assertThat(r.totalActual()).isEqualByComparingTo("600");assertThat(r.totalVariance()).isEqualByComparingTo("400");}

 @Test void periodCloseBlocksPostingAndReopenAllowsIt(){AccountingPeriodServiceImpl s=new AccountingPeriodServiceImpl(periodRepo);AccountingPeriod p=new AccountingPeriod();p.setId(1L);p.setPeriodName("Jan");p.setStartDate(LocalDate.of(2026,1,1));p.setEndDate(LocalDate.of(2026,1,31));p.setStatus(AccountingPeriodStatus.OPEN);when(periodRepo.findById(1L)).thenReturn(Optional.of(p));when(periodRepo.save(any())).thenAnswer(i->i.getArgument(0));assertThat(s.close(1L).getStatus()).isEqualTo(AccountingPeriodStatus.CLOSED);when(periodRepo.contains(LocalDate.of(2026,1,15),AccountingPeriodStatus.CLOSED)).thenReturn(true);assertThatThrownBy(()->s.assertOpen(LocalDate.of(2026,1,15))).isInstanceOf(BadRequestException.class);assertThat(s.reopen(1L).getStatus()).isEqualTo(AccountingPeriodStatus.OPEN);}

 @Test void prepareAndCompleteYearEndAndBlockDuplicate(){YearEndClosingServiceImpl s=yearService();Account income=account(4L,"4000","Sales Income",AccountType.INCOME),expense=account(5L,"5000","Expense",AccountType.EXPENSE),retained=account(3L,"3010","Retained Earnings",AccountType.EQUITY);when(accountRepo.findAll()).thenReturn(List.of(income,expense,retained));stubBalance(4L,"0","500");stubBalance(5L,"100","0");stubBalance(3L,"0","0");when(yearRepo.existsByFiscalYearAndStatusIn(2026,List.of(YearEndClosingStatus.DRAFT,YearEndClosingStatus.COMPLETED))).thenReturn(false,true);when(yearRepo.save(any())).thenAnswer(i->{YearEndClosing y=i.getArgument(0);if(y.getId()==null)y.setId(1L);return y;});YearEndClosing prepared=s.prepare(2026);assertThat(prepared.getRetainedEarningsAmount()).isEqualByComparingTo("400");when(yearRepo.findById(1L)).thenReturn(Optional.of(prepared));when(accountRepo.findByAccountCodeIgnoreCase("3010")).thenReturn(Optional.of(retained));when(journalRepo.findMaxId()).thenReturn(0L);when(journalRepo.save(any())).thenAnswer(i->{JournalEntry j=i.getArgument(0);j.setId(99L);return j;});YearEndClosing done=s.complete(1L);assertThat(done.getStatus()).isEqualTo(YearEndClosingStatus.COMPLETED);assertThat(done.getClosingJournalId()).isEqualTo(99L);assertThatThrownBy(()->s.prepare(2026)).isInstanceOf(BadRequestException.class).hasMessageContaining("already exists");}

 @Test void yearEndBlocksExistingDraftForSameFiscalYear(){YearEndClosingServiceImpl s=yearService();when(yearRepo.existsByFiscalYearAndStatusIn(2026,List.of(YearEndClosingStatus.DRAFT,YearEndClosingStatus.COMPLETED))).thenReturn(true);assertThatThrownBy(()->s.prepare(2026)).isInstanceOf(BadRequestException.class).hasMessageContaining("already exists");}

 @Test void yearEndAndDashboardResolveAccountsByCodeBeforeName(){Account retained=account(3L,"3010","RE Custom",AccountType.EQUITY),cash=account(10L,"1000","Cash Drawer",AccountType.ASSET),bank=account(11L,"1010","Primary Bank",AccountType.ASSET),ar=account(12L,"1020","Trade Receivable",AccountType.ASSET),ap=account(13L,"2000","Trade Payable",AccountType.LIABILITY),income=account(4L,"4000","Sales Income",AccountType.INCOME),expense=account(5L,"5000","Expense",AccountType.EXPENSE);when(accountRepo.findAll()).thenReturn(List.of(retained,cash,bank,ar,ap,income,expense));when(accountRepo.findByAccountCodeIgnoreCase("3010")).thenReturn(Optional.of(retained));when(accountRepo.findByAccountCodeIgnoreCase("1000")).thenReturn(Optional.of(cash));when(accountRepo.findByAccountCodeIgnoreCase("1010")).thenReturn(Optional.of(bank));when(accountRepo.findByAccountCodeIgnoreCase("1020")).thenReturn(Optional.of(ar));when(accountRepo.findByAccountCodeIgnoreCase("2000")).thenReturn(Optional.of(ap));stubBalance(4L,"0","500");stubBalance(5L,"100","0");stubBalance(3L,"0","0");stubBalance(10L,"250","0");stubBalance(11L,"700","0");stubBalance(12L,"120","0");stubBalance(13L,"0","80");when(yearRepo.findById(1L)).thenReturn(Optional.of(yearEnd(1L,2026)));when(yearRepo.save(any())).thenAnswer(i->i.getArgument(0));when(journalRepo.findMaxId()).thenReturn(0L);when(journalRepo.save(any())).thenAnswer(i->{JournalEntry j=i.getArgument(0);j.setId(77L);return j;});YearEndClosing done=yearService().complete(1L);assertThat(done.getClosingJournalId()).isEqualTo(77L);AccountingReportService reports=mock(AccountingReportService.class);BudgetService budgets=mock(BudgetService.class);when(reports.getProfitLoss(any(),any())).thenReturn(new ProfitLossDTO(List.of(),List.of(),new BigDecimal("500"),new BigDecimal("100"),new BigDecimal("400"),false,BigDecimal.ZERO));when(reports.getTrialBalance(any(),any())).thenReturn(new TrialBalanceDTO(List.of(),BigDecimal.ZERO,BigDecimal.ZERO));when(budgets.actual(any(),any(),any(),any(),any())).thenReturn(new BudgetActualDTO(List.of(),BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO,BigDecimal.ZERO));FinancialDashboardDTO dashboard=new FinancialDashboardServiceImpl(accountRepo,lineRepo,reports,budgets).get(2026);assertThat(dashboard.cashBalance()).isEqualByComparingTo("250");assertThat(dashboard.bankBalance()).isEqualByComparingTo("700");assertThat(dashboard.accountsReceivable()).isEqualByComparingTo("120");assertThat(dashboard.accountsPayable()).isEqualByComparingTo("80");}

 private BudgetServiceImpl budgetService(){return new BudgetServiceImpl(budgetRepo,accountRepo,centerRepo,lineRepo);} private YearEndClosingServiceImpl yearService(){return new YearEndClosingServiceImpl(yearRepo,accountRepo,journalRepo,lineRepo,periodService);}
 private YearEndClosing yearEnd(Long id,int year){YearEndClosing y=new YearEndClosing();y.setId(id);y.setFiscalYear(year);y.setClosingDate(LocalDate.of(year,12,31));y.setStatus(YearEndClosingStatus.DRAFT);return y;}
 private BudgetDTO budgetDto(){BudgetDTO d=new BudgetDTO();d.setFiscalYear(2026);d.setPeriodType(BudgetPeriodType.YEARLY);d.setFromDate(LocalDate.of(2026,1,1));d.setToDate(LocalDate.of(2026,12,31));d.setAccountId(1L);d.setAmount(new BigDecimal("1000"));return d;}
 private Budget budgetEntity(Long id,Account a,BudgetStatus st){Budget b=new Budget();b.setId(id);b.setBudgetNo("BUD-0001");b.setFiscalYear(2026);b.setPeriodType(BudgetPeriodType.YEARLY);b.setFromDate(LocalDate.of(2026,1,1));b.setToDate(LocalDate.of(2026,12,31));b.setAccount(a);b.setAmount(new BigDecimal("1000"));b.setStatus(st);return b;}
 private CostCenter center(Long id){CostCenter c=new CostCenter();c.setId(id);c.setCode("OPS");c.setName("Operations");c.setStatus(Status.ACTIVE);return c;} private Account account(Long id,String code,String name,AccountType type){Account a=new Account();a.setId(id);a.setAccountCode(code);a.setAccountName(name);a.setAccountType(type);a.setStatus(Status.ACTIVE);return a;}
 private JournalEntryLine line(Account a,String d,String c,CostCenter cc){JournalEntry j=new JournalEntry();j.setJournalDate(LocalDate.now());j.setStatus(JournalStatus.POSTED);JournalEntryLine l=new JournalEntryLine();l.setAccount(a);l.setDebit(new BigDecimal(d));l.setCredit(new BigDecimal(c));l.setCostCenter(cc);j.addLine(l);return l;} private void stubBalance(Long id,String d,String c){lenient().when(lineRepo.sumDebit(eq(id),nullable(LocalDate.class),nullable(LocalDate.class))).thenReturn(new BigDecimal(d));lenient().when(lineRepo.sumCredit(eq(id),nullable(LocalDate.class),nullable(LocalDate.class))).thenReturn(new BigDecimal(c));}
}
