import { Component, OnInit } from '@angular/core';
import { AbstractControl, FormBuilder, FormGroup, ValidationErrors, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { Customer } from '../../../models/customer.model';
import { Status } from '../../../models/product.model';
import { CustomerService } from '../../../services/customer.service';
import { debugApiError, extractApiErrorMessage } from '../../../shared/utils/api-error.util';

@Component({
  selector: 'app-customer-form',
  templateUrl: './customer-form.component.html',
  styleUrls: ['./customer-form.component.css']
})
export class CustomerFormComponent implements OnInit {
  private readonly autoGeneratedCodeLabel = 'Auto generated by backend';

  form: FormGroup;
  loading = false;
  submitting = false;
  isEditMode = false;
  customerId: number | null = null;
  errorMessage = '';

  readonly statusList: Status[] = ['ACTIVE', 'INACTIVE'];

  constructor(
    private fb: FormBuilder,
    private route: ActivatedRoute,
    private router: Router,
    private customerService: CustomerService
  ) {
    this.form = this.fb.group({
      customerCode: [{ value: '', disabled: true }],
      name: ['', [Validators.required, this.notBlankValidator, Validators.maxLength(255)]],
      companyName: ['', [Validators.maxLength(255)]],
      contactPerson: ['', [Validators.maxLength(255)]],
      phone: ['', [Validators.maxLength(100)]],
      email: ['', [Validators.email, Validators.maxLength(255)]],
      address: [''],
      city: ['', [Validators.maxLength(100)]],
      country: ['', [Validators.maxLength(100)]],
      postalCode: ['', [Validators.maxLength(50)]],
      creditLimit: [0, [Validators.min(0)]],
      openingBalance: [0, [Validators.min(0)]],
      currentBalance: [0],
      taxNumber: ['', [Validators.maxLength(100)]],
      status: ['ACTIVE', Validators.required]
    });
  }

  ngOnInit(): void {
    const idParam = this.route.snapshot.paramMap.get('id');
    if (idParam) {
      this.customerId = Number(idParam);
      this.isEditMode = true;
      this.loadCustomer(this.customerId);
    } else {
      this.form.patchValue({
        customerCode: this.autoGeneratedCodeLabel,
        creditLimit: 0,
        openingBalance: 0,
        currentBalance: 0,
        status: 'ACTIVE'
      });
    }
  }

  loadCustomer(id: number): void {
    this.loading = true;
    this.customerService.getCustomerById(id).subscribe({
      next: (customer) => {
        this.form.patchValue({
          customerCode: customer.customerCode || this.autoGeneratedCodeLabel,
          name: customer.name,
          companyName: customer.companyName || '',
          contactPerson: customer.contactPerson || '',
          phone: customer.phone || '',
          email: customer.email || '',
          address: customer.address || '',
          city: customer.city || '',
          country: customer.country || '',
          postalCode: customer.postalCode || '',
          creditLimit: customer.creditLimit ?? 0,
          openingBalance: customer.openingBalance ?? 0,
          currentBalance: customer.currentBalance ?? (customer.openingBalance ?? 0),
          taxNumber: customer.taxNumber || '',
          status: customer.status || 'ACTIVE'
        });
        this.loading = false;
      },
      error: (error) => {
        this.errorMessage = extractApiErrorMessage(error, 'Customer could not be loaded.');
        this.loading = false;
        debugApiError('CustomerFormComponent.loadCustomer', error);
      }
    });
  }

  submit(): void {
    this.errorMessage = '';
    if (this.form.invalid) {
      this.form.markAllAsTouched();
      return;
    }

    const payload = this.buildPayload();
    this.submitting = true;

    const request$ = this.isEditMode && this.customerId
      ? this.customerService.updateCustomer(this.customerId, payload)
      : this.customerService.createCustomer(payload);

    request$.subscribe({
      next: () => {
        this.submitting = false;
        this.router.navigate(['/customers/list']);
      },
      error: (error) => {
        this.submitting = false;
        this.errorMessage = extractApiErrorMessage(error, 'Customer could not be saved.');
        debugApiError('CustomerFormComponent.submit', error);
      }
    });
  }

  cancel(): void {
    this.router.navigate(['/customers/list']);
  }

  hasError(controlName: string, errorName: string): boolean {
    const control = this.form.get(controlName);
    return !!control && control.touched && control.hasError(errorName);
  }

  private buildPayload(): Customer {
    const value = this.form.getRawValue();
    return {
      customerCode: this.buildCustomerCode(value.customerCode),
      name: value.name.trim(),
      companyName: this.optionalTextValue(value.companyName),
      contactPerson: this.optionalTextValue(value.contactPerson),
      phone: this.optionalTextValue(value.phone),
      email: this.optionalTextValue(value.email),
      address: this.optionalTextValue(value.address),
      city: this.optionalTextValue(value.city),
      country: this.optionalTextValue(value.country),
      postalCode: this.optionalTextValue(value.postalCode),
      creditLimit: value.creditLimit === null || value.creditLimit === '' ? 0 : Number(value.creditLimit),
      openingBalance: value.openingBalance === null || value.openingBalance === '' ? 0 : Number(value.openingBalance),
      currentBalance: this.isEditMode
        ? (value.currentBalance === null || value.currentBalance === '' ? 0 : Number(value.currentBalance))
        : undefined,
      taxNumber: this.optionalTextValue(value.taxNumber),
      status: value.status
    };
  }

  private notBlankValidator(control: AbstractControl): ValidationErrors | null {
    return typeof control.value === 'string' && control.value.trim().length === 0
      ? { required: true }
      : null;
  }

  private buildCustomerCode(value: string): string | undefined {
    if (!this.isEditMode) {
      return undefined;
    }

    const customerCode = value?.trim();
    return customerCode && customerCode !== this.autoGeneratedCodeLabel
      ? customerCode
      : undefined;
  }

  private optionalTextValue(value: string): string | null | undefined {
    const normalized = value?.trim();
    if (normalized) {
      return normalized;
    }
    return this.isEditMode ? null : undefined;
  }
}
