package com.sme.erp.accounting.controller;
import com.sme.erp.accounting.dto.CostCenterDTO; import com.sme.erp.accounting.service.CostCenterService; import com.sme.erp.enums.Status; import org.springframework.data.domain.Page; import org.springframework.http.*; import org.springframework.security.access.prepost.PreAuthorize; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/v1/accounting/cost-centers") public class CostCenterController { private final CostCenterService service; public CostCenterController(CostCenterService s){service=s;}
 @GetMapping @PreAuthorize("hasAnyAuthority('COST_CENTER_VIEW','ACCOUNTING_VIEW','ACCOUNTING_CREATE','ACCOUNTING_EDIT','BUDGET_VIEW','BUDGET_CREATE','BUDGET_EDIT')") public List<CostCenterDTO> all(){return service.all();}
 @GetMapping("/page") @PreAuthorize("hasAnyAuthority('COST_CENTER_VIEW','ACCOUNTING_VIEW','ACCOUNTING_CREATE','ACCOUNTING_EDIT','BUDGET_VIEW','BUDGET_CREATE','BUDGET_EDIT')") public Page<CostCenterDTO> page(@RequestParam(required=false)String keyword,@RequestParam(required=false)Status status,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="10")int size){return service.page(keyword,status,page,size);}
 @GetMapping("/{id}") @PreAuthorize("hasAnyAuthority('COST_CENTER_VIEW','ACCOUNTING_VIEW','ACCOUNTING_CREATE','ACCOUNTING_EDIT','BUDGET_VIEW','BUDGET_CREATE','BUDGET_EDIT')") public CostCenterDTO get(@PathVariable Long id){return service.get(id);}
 @PostMapping @PreAuthorize("hasAuthority('COST_CENTER_CREATE')") public CostCenterDTO create(@RequestBody CostCenterDTO d){return service.create(d);}
 @PutMapping("/{id}") @PreAuthorize("hasAuthority('COST_CENTER_EDIT')") public CostCenterDTO update(@PathVariable Long id,@RequestBody CostCenterDTO d){return service.update(id,d);}
 @DeleteMapping("/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) @PreAuthorize("hasAuthority('COST_CENTER_DELETE')") public void delete(@PathVariable Long id){service.deactivate(id);}
}
