import { Component, OnInit } from '@angular/core';
import { FormArray, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { InventoryWarehouse } from '../../../models/inventory-warehouse.model';
import { Product, Status } from '../../../models/product.model';
import { PurchaseItem, PurchaseOrder, PurchaseStatus } from '../../../models/purchase.model';
import { Supplier } from '../../../models/supplier.model';
import { Uom } from '../../../models/uom.model';
import { InventoryWarehouseService } from '../../../services/inventory-warehouse.service';
import { ProductService } from '../../../services/product.service';
import { PurchaseService } from '../../../services/purchase.service';
import { SupplierService } from '../../../services/supplier.service';
import { UomService } from '../../../services/uom.service';
import { debugApiError, extractApiErrorMessage } from '../../../shared/utils/api-error.util';

@Component({
  selector: 'app-purchase-order',
  templateUrl: './purchase-order.component.html',
  styleUrls: ['./purchase-order.component.css']
})
export class PurchaseOrderComponent implements OnInit {
  form: FormGroup;
  orders: PurchaseOrder[] = [];
  suppliers: Supplier[] = [];
  warehouses: InventoryWarehouse[] = [];
  products: Product[] = [];
  uoms: Uom[] = [];
  loading = false;
  submitting = false;
  successMessage = '';
  errorMessage = '';
  selectedOrder: PurchaseOrder | null = null;
  editingOrderId: number | null = null;

  readonly statuses: PurchaseStatus[] = ['DRAFT', 'PENDING', 'APPROVED', 'RECEIVED', 'PARTIAL_PAID', 'PAID', 'CANCELLED'];
  readonly activeStatus: Status = 'ACTIVE';

  constructor(
    private fb: FormBuilder,
    private purchaseService: PurchaseService,
    private supplierService: SupplierService,
    private warehouseService: InventoryWarehouseService,
    private productService: ProductService,
    private uomService: UomService
  ) {
    this.form = this.fb.group({
      purchaseCode: [{ value: 'Auto generated by backend', disabled: true }],
      supplierId: [null, Validators.required],
      warehouseId: [null, Validators.required],
      purchaseDate: [this.today(), Validators.required],
      status: ['PENDING', Validators.required],
      paidAmount: [0, [Validators.required, Validators.min(0)]],
      items: this.fb.array([])
    });
    this.addItem();
  }

  ngOnInit(): void {
    this.loadOrders();
    this.loadReferenceData();
  }

  get items(): FormArray {
    return this.form.get('items') as FormArray;
  }

  get totalAmount(): number {
    return this.items.controls.reduce((sum, control) => {
      const quantity = Number(control.get('quantity')?.value || 0);
      const unitPrice = Number(control.get('unitPrice')?.value || 0);
      return sum + (quantity * unitPrice);
    }, 0);
  }

  get discountAmount(): number {
    return this.items.controls.reduce((sum, control) => sum + Number(control.get('discount')?.value || 0), 0);
  }

  get taxAmount(): number {
    return this.items.controls.reduce((sum, control) => sum + Number(control.get('tax')?.value || 0), 0);
  }

  get netTotal(): number {
    return this.totalAmount - this.discountAmount + this.taxAmount;
  }

  get dueAmount(): number {
    return Math.max(this.netTotal - Number(this.form.get('paidAmount')?.value || 0), 0);
  }

  loadOrders(): void {
    this.loading = true;
    this.purchaseService.getAllOrders().subscribe({
      next: (orders) => {
        this.orders = orders;
        this.selectedOrder = orders[0] || null;
        this.loading = false;
      },
      error: (error) => {
        this.orders = [];
        this.selectedOrder = null;
        this.loading = false;
        this.errorMessage = extractApiErrorMessage(error, 'Purchase orders could not be loaded.');
        debugApiError('PurchaseOrderComponent.loadOrders', error);
      }
    });
  }

  loadReferenceData(): void {
    this.supplierService.getAllSuppliers('', this.activeStatus).subscribe({
      next: suppliers => this.suppliers = suppliers,
      error: error => debugApiError('PurchaseOrderComponent.loadSuppliers', error)
    });

    this.warehouseService.getAllWarehouses().subscribe({
      next: warehouses => this.warehouses = warehouses,
      error: error => debugApiError('PurchaseOrderComponent.loadWarehouses', error)
    });

    this.productService.getAllProducts().subscribe({
      next: products => this.products = products,
      error: error => debugApiError('PurchaseOrderComponent.loadProducts', error)
    });

    this.uomService.getAllUoms().subscribe({
      next: uoms => this.uoms = uoms,
      error: error => debugApiError('PurchaseOrderComponent.loadUoms', error)
    });
  }

  addItem(item?: Partial<PurchaseItem>): void {
    const group = this.fb.group({
      productId: [item?.productId ?? null, Validators.required],
      uomId: [item?.uomId ?? null],
      quantity: [item?.quantity ?? 1, [Validators.required, Validators.min(0.01)]],
      unitPrice: [item?.unitPrice ?? 0, [Validators.required, Validators.min(0)]],
      discount: [item?.discount ?? 0, [Validators.required, Validators.min(0)]],
      tax: [item?.tax ?? 0, [Validators.required, Validators.min(0)]],
      subTotal: [{ value: item?.subTotal ?? 0, disabled: true }]
    });

    ['quantity', 'unitPrice', 'discount', 'tax'].forEach(field => {
      group.get(field)?.valueChanges.subscribe(() => this.recalculateRow(group));
    });

    this.items.push(group);
    this.recalculateRow(group);
  }

  removeItem(index: number): void {
    if (this.items.length === 1) {
      return;
    }
    this.items.removeAt(index);
  }

  onProductChange(index: number): void {
    const group = this.items.at(index) as FormGroup;
    const product = this.products.find(item => item.id === Number(group.get('productId')?.value));
    if (product) {
      group.patchValue({
        unitPrice: product.purchasePrice || 0,
        uomId: product.uomId ?? null
      }, { emitEvent: true });
    }
  }

  recalculateRow(group: FormGroup): void {
    const quantity = Number(group.get('quantity')?.value || 0);
    const unitPrice = Number(group.get('unitPrice')?.value || 0);
    const discount = Number(group.get('discount')?.value || 0);
    const tax = Number(group.get('tax')?.value || 0);
    const subTotal = (quantity * unitPrice) - discount + tax;
    group.get('subTotal')?.setValue(subTotal, { emitEvent: false });
  }

  editOrder(order: PurchaseOrder): void {
    if (!order.id) {
      return;
    }

    this.purchaseService.getOrderById(order.id).subscribe({
      next: (fullOrder) => {
        this.editingOrderId = fullOrder.id || null;
        this.selectedOrder = fullOrder;
        this.patchForm(fullOrder);
        this.successMessage = '';
        this.errorMessage = '';
      },
      error: (error) => {
        this.errorMessage = extractApiErrorMessage(error, 'Purchase order could not be loaded for editing.');
        debugApiError('PurchaseOrderComponent.editOrder', error);
      }
    });
  }

  saveOrder(): void {
    this.successMessage = '';
    this.errorMessage = '';

    if (this.form.invalid || this.items.length === 0) {
      this.form.markAllAsTouched();
      this.items.controls.forEach(control => control.markAllAsTouched());
      return;
    }

    this.submitting = true;
    const payload = this.buildPayload();

    this.purchaseService.saveOrder(payload).subscribe({
      next: (saved) => {
        this.submitting = false;
        this.successMessage = this.editingOrderId ? 'Purchase order updated successfully.' : 'Purchase order saved successfully.';
        this.selectedOrder = saved;
        this.loadOrders();
        this.resetForm();
      },
      error: (error) => {
        this.submitting = false;
        this.errorMessage = extractApiErrorMessage(error, 'Purchase order could not be saved.');
        debugApiError('PurchaseOrderComponent.saveOrder', error);
      }
    });
  }

  resetForm(): void {
    this.editingOrderId = null;
    while (this.items.length > 0) {
      this.items.removeAt(0);
    }

    this.form.reset({
      purchaseCode: 'Auto generated by backend',
      supplierId: null,
      warehouseId: null,
      purchaseDate: this.today(),
      status: 'PENDING',
      paidAmount: 0
    });
    this.addItem();
  }

  statusClass(status?: PurchaseStatus): string {
    switch (status) {
      case 'PAID':
      case 'RECEIVED':
        return 'bg-success-subtle text-success';
      case 'APPROVED':
      case 'PARTIAL_PAID':
        return 'bg-info-subtle text-info';
      case 'CANCELLED':
        return 'bg-danger-subtle text-danger';
      case 'DRAFT':
        return 'bg-secondary-subtle text-secondary';
      default:
        return 'bg-warning-subtle text-warning';
    }
  }

  hasError(path: string, errorName: string): boolean {
    const control = this.form.get(path);
    return !!control && control.touched && control.hasError(errorName);
  }

  private patchForm(order: PurchaseOrder): void {
    while (this.items.length > 0) {
      this.items.removeAt(0);
    }

    this.form.patchValue({
      purchaseCode: order.purchaseCode || 'Auto generated by backend',
      supplierId: order.supplierId,
      warehouseId: order.warehouseId,
      purchaseDate: this.toDateInput(order.purchaseDate),
      status: order.status || 'PENDING',
      paidAmount: order.paidAmount ?? 0
    });

    if (!order.items.length) {
      this.addItem();
      return;
    }

    order.items.forEach(item => this.addItem(item));
  }

  private buildPayload(): PurchaseOrder {
    const value = this.form.getRawValue();
    const supplier = this.suppliers.find(item => item.id === Number(value.supplierId));
    const warehouse = this.warehouses.find(item => item.id === Number(value.warehouseId));
    const items: PurchaseItem[] = value.items.map((item: any) => ({
      productId: item.productId !== null ? Number(item.productId) : null,
      productName: this.products.find(product => product.id === Number(item.productId))?.productName || 'N/A',
      uomId: item.uomId !== null && item.uomId !== '' ? Number(item.uomId) : null,
      uomName: this.uoms.find(uom => uom.id === Number(item.uomId))?.name || '',
      quantity: Number(item.quantity || 0),
      unitPrice: Number(item.unitPrice || 0),
      discount: Number(item.discount || 0),
      tax: Number(item.tax || 0),
      subTotal: Number(item.subTotal || 0)
    }));

    return {
      id: this.editingOrderId || undefined,
      purchaseCode: this.editingOrderId ? value.purchaseCode : undefined,
      supplierId: value.supplierId !== null ? Number(value.supplierId) : null,
      supplierName: supplier?.name || '',
      warehouseId: value.warehouseId !== null ? Number(value.warehouseId) : null,
      warehouseName: warehouse?.name || '',
      purchaseDate: value.purchaseDate,
      totalAmount: this.totalAmount,
      discountAmount: this.discountAmount,
      taxAmount: this.taxAmount,
      netTotal: this.netTotal,
      paidAmount: Number(value.paidAmount || 0),
      dueAmount: this.dueAmount,
      status: value.status,
      items
    };
  }

  private today(): string {
    return new Date().toISOString().slice(0, 10);
  }

  private toDateInput(value?: string): string {
    return value ? value.slice(0, 10) : this.today();
  }
}
