import { Component, OnInit } from '@angular/core';
import { FormArray, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Product } from '../../../models/product.model';
import { PurchaseOrder, PurchaseReturn, PurchaseReturnItem } from '../../../models/purchase.model';
import { Supplier } from '../../../models/supplier.model';
import { ProductService } from '../../../services/product.service';
import { PurchaseService } from '../../../services/purchase.service';
import { SupplierService } from '../../../services/supplier.service';
import { debugApiError, extractApiErrorMessage } from '../../../shared/utils/api-error.util';

@Component({
  selector: 'app-purchase-return',
  templateUrl: './purchase-return.component.html',
  styleUrls: ['./purchase-return.component.css']
})
export class PurchaseReturnComponent implements OnInit {
  form: FormGroup;
  returns: PurchaseReturn[] = [];
  purchases: PurchaseOrder[] = [];
  suppliers: Supplier[] = [];
  products: Product[] = [];
  selectedReturn: PurchaseReturn | null = null;
  loading = false;
  submitting = false;
  successMessage = '';
  errorMessage = '';

  constructor(
    private fb: FormBuilder,
    private purchaseService: PurchaseService,
    private supplierService: SupplierService,
    private productService: ProductService
  ) {
    this.form = this.fb.group({
      returnCode: [{ value: 'Auto generated by backend', disabled: true }],
      purchaseId: [null, Validators.required],
      supplierId: [null, Validators.required],
      returnDate: [this.today(), Validators.required],
      items: this.fb.array([])
    });
    this.addItem();
  }

  ngOnInit(): void {
    this.loadReturns();
    this.loadReferenceData();
  }

  get items(): FormArray {
    return this.form.get('items') as FormArray;
  }

  get totalAmount(): number {
    return this.items.controls.reduce((sum, control) => sum + Number(control.get('total')?.value || 0), 0);
  }

  loadReturns(selectedId?: number): void {
    this.loading = true;
    this.purchaseService.getAllReturns().subscribe({
      next: (returns) => {
        this.returns = returns;
        this.selectedReturn = returns.find(item => item.id === selectedId) || returns[0] || null;
        this.loading = false;
      },
      error: (error) => {
        this.returns = [];
        this.selectedReturn = null;
        this.loading = false;
        this.errorMessage = extractApiErrorMessage(error, 'Purchase returns could not be loaded.');
        debugApiError('PurchaseReturnComponent.loadReturns', error);
      }
    });
  }

  loadReferenceData(): void {
    this.purchaseService.getAllOrders().subscribe({
      next: purchases => this.purchases = purchases,
      error: error => debugApiError('PurchaseReturnComponent.loadPurchases', error)
    });

    this.supplierService.getAllSuppliers().subscribe({
      next: suppliers => this.suppliers = suppliers,
      error: error => debugApiError('PurchaseReturnComponent.loadSuppliers', error)
    });

    this.productService.getAllProducts().subscribe({
      next: products => this.products = products,
      error: error => debugApiError('PurchaseReturnComponent.loadProducts', error)
    });
  }

  addItem(item?: Partial<PurchaseReturnItem>): void {
    const group = this.fb.group({
      productId: [item?.productId ?? null, Validators.required],
      quantity: [item?.quantity ?? 1, [Validators.required, Validators.min(0.01)]],
      unitPrice: [item?.unitPrice ?? 0, [Validators.required, Validators.min(0)]],
      total: [{ value: item?.total ?? 0, disabled: true }]
    });

    ['quantity', 'unitPrice'].forEach(field => {
      group.get(field)?.valueChanges.subscribe(() => this.recalculateRow(group));
    });

    this.items.push(group);
    this.recalculateRow(group);
  }

  removeItem(index: number): void {
    if (this.items.length === 1) {
      return;
    }
    this.items.removeAt(index);
  }

  onPurchaseChange(): void {
    const purchaseId = Number(this.form.get('purchaseId')?.value || 0);
    const purchase = this.purchases.find(item => item.id === purchaseId);
    if (!purchase) {
      return;
    }

    while (this.items.length > 0) {
      this.items.removeAt(0);
    }

    this.form.patchValue({
      supplierId: purchase.supplierId
    });

    if (!purchase.items.length) {
      this.addItem();
      return;
    }

    purchase.items.forEach(item => this.addItem({
      productId: item.productId,
      quantity: item.quantity,
      unitPrice: item.unitPrice,
      total: item.quantity * item.unitPrice
    }));
  }

  recalculateRow(group: FormGroup): void {
    const quantity = Number(group.get('quantity')?.value || 0);
    const unitPrice = Number(group.get('unitPrice')?.value || 0);
    const total = quantity * unitPrice;
    group.get('total')?.setValue(total, { emitEvent: false });
  }

  saveReturn(): void {
    this.successMessage = '';
    this.errorMessage = '';

    if (this.form.invalid || this.items.length === 0) {
      this.form.markAllAsTouched();
      this.items.controls.forEach(control => control.markAllAsTouched());
      return;
    }

    this.submitting = true;
    const payload = this.buildPayload();

    this.purchaseService.saveReturn(payload).subscribe({
      next: (saved) => {
        this.submitting = false;
        this.successMessage = 'Purchase return saved successfully.';
        this.selectedReturn = saved;
        this.resetForm();
        this.loadReturns(saved.id);
      },
      error: (error) => {
        this.submitting = false;
        this.errorMessage = extractApiErrorMessage(error, 'Purchase return could not be saved.');
        debugApiError('PurchaseReturnComponent.saveReturn', error);
      }
    });
  }

  resetForm(): void {
    while (this.items.length > 0) {
      this.items.removeAt(0);
    }

    this.form.reset({
      returnCode: 'Auto generated by backend',
      purchaseId: null,
      supplierId: null,
      returnDate: this.today()
    });
    this.addItem();
  }

  hasError(path: string, errorName: string): boolean {
    const control = this.form.get(path);
    return !!control && control.touched && control.hasError(errorName);
  }

  selectReturn(purchaseReturn: PurchaseReturn): void {
    if (!purchaseReturn.id) {
      this.selectedReturn = purchaseReturn;
      return;
    }

    this.purchaseService.getReturnById(purchaseReturn.id).subscribe({
      next: (fullReturn) => {
        this.selectedReturn = fullReturn;
      },
      error: (error) => {
        this.errorMessage = extractApiErrorMessage(error, 'Purchase return details could not be loaded.');
        debugApiError('PurchaseReturnComponent.selectReturn', error);
      }
    });
  }

  private buildPayload(): PurchaseReturn {
    const value = this.form.getRawValue();
    const purchase = this.purchases.find(item => item.id === Number(value.purchaseId));
    const supplier = this.suppliers.find(item => item.id === Number(value.supplierId));
    const items: PurchaseReturnItem[] = value.items.map((item: any) => ({
      productId: item.productId !== null ? Number(item.productId) : null,
      productName: this.products.find(product => product.id === Number(item.productId))?.productName || 'N/A',
      quantity: Number(item.quantity || 0),
      unitPrice: Number(item.unitPrice || 0),
      total: Number(item.total || 0)
    }));

    return {
      purchaseId: value.purchaseId !== null ? Number(value.purchaseId) : null,
      purchaseCode: purchase?.purchaseCode || '',
      supplierId: value.supplierId !== null ? Number(value.supplierId) : null,
      supplierName: supplier?.name || '',
      returnDate: value.returnDate,
      items,
      totalAmount: items.reduce((sum, item) => sum + item.total, 0)
    };
  }

  private today(): string {
    return new Date().toISOString().slice(0, 10);
  }
}
